const currencies: string[] = [
  'US Dollar (USD)',
  'Euro (EUR)',
  'Japanese Yen (JPY)',
  'British Pound (GBP)',
  'Australian Dollar (AUD)',
  'Canadian Dollar (CAD)',
  'Swiss Franc (CHF)',
  'Chinese Yuan (CNY)',
  'Swedish Krona (SEK)',
  'New Zealand Dollar (NZD)',
  'Norwegian Krone (NOK)',
  'South Korean Won (KRW)',
  'Turkish Lira (TRY)',
  'Russian Ruble (RUB)',
  'Indian Rupee (INR)',
  'Brazilian Real (BRL)',
  'South African Rand (ZAR)',
  'UAE Dirham (AED)',
  'Mexican Peso (MXN)',
  'Singapore Dollar (SGD)',
  'Nigerian Naira (NGN)',
  'Philippine Peso (PHP)',
  'Malaysian Ringgit (MYR)',
  'Indonesian Rupiah (IDR)',
  'Thai Baht (THB)',
  'Saudi Riyal (SAR)',
  'Qatari Riyal (QAR)',
  'Danish Krone (DKK)',
  'Hungarian Forint (HUF)',
  'Czech Koruna (CZK)',
];

export default currencies;
