#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
 
echo 'Checking your code for errors...'
echo 'Please be patient, this may take a while...'
 
# Check ESLint Standards
npm run lint ||
(
    echo '⚠️ ❌ You have a problem in your code. Fix the error and try again ❌⚠️
          you can run "npm run lint" to see the error';
    false;
)
 
echo 'Committing...'
 
npx lint-staged